### ISSUE TITLE
Login with google is broken

### ISSUE THREAD

**Issue by ronniebarker** [abacritt/angularx-social-login#720]
I think there must have been a change to the google API:

![image](https://github.com/abacritt/angularx-social-login/assets/129157/b0e50e80-9c63-44ff-b607-a9069dcf1b6a)

![image](https://github.com/abacritt/angularx-social-login/assets/129157/07008a19-2348-4704-8277-c6982caaeae8)

**Comment by ronniebarker** [comment]
Seems to be only when we have `width='nnn'` in the `asl-google-signin-button` - but why is that breaking it and why now?

**Comment by exptom** [comment]
I'm getting the same error when I specify the width attribute. I can't see a change in google's docs.

**Comment by giacomodefra** [comment]
![image](https://github.com/abacritt/angularx-social-login/assets/38209135/0efad727-d90a-4bd3-bff2-7f427cf01e22)

I have the same problem, I haven't made any recent changes and my applications worked perfectly with the login, now I have this error in the console.

**Comment by aluuu** [comment]
It seems like google's client library stopped accepting numbers-as-strings if provided as an input to the `renderButton` function.

Example to reproduce:
```html
<html>
<head>
  <meta name="google-signin-client_id" content="YOUR_CLIENT_ID.apps.googleusercontent.com">
</head>
<body>
  <div id="my-signin2"></div>
  <script src="https://accounts.google.com/gsi/client"></script>
  <script>
    google.accounts.id.initialize();
    google.accounts.id.renderButton(document.getElementById('my-signin2'), {
    'width': 200,
    });
  </script>
</body>
</html>
```

If `width` passed as a number - all works button is rendered, once quoted - it fails with the following (similar to the above) stacktrace:
```
Uncaught Error: 
    $e https://accounts.google.com/gsi/client:128
    qp https://accounts.google.com/gsi/client:226
    $p https://accounts.google.com/gsi/client:245
    Mo https://accounts.google.com/gsi/client:243
    No https://accounts.google.com/gsi/client:215
    <anonymous> http://localhost:8000/google.html:10
```

**Comment by aluuu** [comment]
Google's API documentation says that width is [expected to be a string](https://developers.google.com/identity/gsi/web/reference/js-reference#width).

**Comment by aluuu** [comment]
I've posted a message with link to this issue via feedback form on the Google's [documentation page](https://developers.google.com/identity/gsi/web/reference/js-reference) (see button 'Send feedback'). 

I'd suggest to people who face the same issue - post the reports there because it's either documentation should be fixed or the library's implementation should conform with the documentation. Authors of angularx-social-login could potentially fix the issue at hand, but you never know when Google would decide to change the library implementation again.

**Comment by Nas3nmann** [comment]
FYI: For now we managed to workaround this issue by providing the width value including `px` suffix.
```
<asl-google-signin-button type="standard" logo_alignment="center"  width="240px" size="large"></asl-google-signin-button>
```

**Comment by gedkul** [comment]
![image](https://github.com/abacritt/angularx-social-login/assets/28755475/20d51c6a-9b01-465d-bb2c-723a1aa5ae3e)
Strange that in dev pc login button is showing on all browsers, but in different pc or mobile google login button is missing.
And showing:
![image](https://github.com/abacritt/angularx-social-login/assets/28755475/0275a100-f1b5-466f-b5de-fbbccf511cc7)
![image](https://github.com/abacritt/angularx-social-login/assets/28755475/a3d2415b-d8bb-4a22-9451-8099197866ea)
![image](https://github.com/abacritt/angularx-social-login/assets/28755475/f9273511-b831-4fdd-9166-1feb7043b2dd)

**Comment by AntoninKadrmas** [comment]
> ![image](https://user-images.githubusercontent.com/28755475/256319497-20d51c6a-9b01-465d-bb2c-723a1aa5ae3e.png) Strange that in dev pc login button is showing on all browsers, but in different pc or mobile google login button is missing. And showing: ![image](https://user-images.githubusercontent.com/28755475/256320080-0275a100-f1b5-466f-b5de-fbbccf511cc7.png) ![image](https://user-images.githubusercontent.com/28755475/256320296-a3d2415b-d8bb-4a22-9451-8099197866ea.png) ![image](https://user-images.githubusercontent.com/28755475/256319864-f9273511-b831-4fdd-9166-1feb7043b2dd.png)
> 
> Edit: Found that button request has 403 response code ![image](https://user-images.githubusercontent.com/28755475/256321240-0a84a553-436e-4416-9697-0b739347b63e.png)
> 
> Edit2: Removed width attribute and working now: ` <asl-google-signin-button title='Google' type='standard' size='large' theme="outline" shape="square" locale="en_US" text="signin"></asl-google-signin-button>`

Hi I had same problem and I fixed it by changing property `width="300"` of `asl-google-signin-button` component to `width="300px"`.

**Comment by gedkul** [comment]
> Hi I had same problem and I fixed it by changing property `width="300"` of `asl-google-signin-button` component to `width="300px"`.

This doesn't fully fix problem. Its shows button but doesn't gives 300px width.

**Comment by gedkul** [comment]
Found that in Google documentation is the same problem. 
![image](https://github.com/abacritt/angularx-social-login/assets/28755475/75c4eeb9-f438-44f6-bceb-b9e68c19ea34)

And when width is removed button is showing:
![image](https://github.com/abacritt/angularx-social-login/assets/28755475/d10357e0-c376-4551-b8cd-6fa8df38a7b6)

**Comment by AntoninKadrmas** [comment]
![image](https://github.com/abacritt/angularx-social-login/assets/113413825/b8570fde-ad08-4d04-af12-dd7068f81038)
Hi I found the same page and with `px` suffix it work for me as I expected. 

And if you add in your code `style="width:300px"` (or whatever else length you are looking for) on `asl-google-signin-button` component it will have the correct length from the begining when the button is loaded. Else it will load shrink and then it will dynamically resize on specified length.

**Comment by hoi4** [comment]
I have been using `width="400"` before. Using `width="400px"` causes the library to error. A temporary fix is to use `width="399px"`

**Comment by giacomodefra** [comment]
I fixed using the proprety with [width]="400" (not width="400")

` <asl-google-signin-button type="standard" size="large" [width]="400" class="mx-5"></asl-google-signin-button>`

**Comment by formyjobonly** [comment]
> I've posted a message with link to this issue via feedback form on the Google's [documentation page](https://developers.google.com/identity/gsi/web/reference/js-reference) (see button 'Send feedback').
> 
> I'd suggest to people who face the same issue - post the reports there because it's either documentation should be fixed or the library's implementation should conform with the documentation. Authors of angularx-social-login could potentially fix the issue at hand, but you never know when Google would decide to change the library implementation again.

@aluuu any updates?

**Comment by jpike88** [comment]
classic google junk.

adding 'px' on the end of my width amount worked but I had css animations showing the div it was in, now it causes some kind of reflow at the end, and the animation 'clunks' when finished into the final look.

**Comment by aluuu** [comment]
> > I've posted a message with link to this issue via feedback form on the Google's [documentation page](https://developers.google.com/identity/gsi/web/reference/js-reference) (see button 'Send feedback').
> > I'd suggest to people who face the same issue - post the reports there because it's either documentation should be fixed or the library's implementation should conform with the documentation. Authors of angularx-social-login could potentially fix the issue at hand, but you never know when Google would decide to change the library implementation again.
> 
> @aluuu any updates?

Nope, no one replied yet.

**Comment by chiragdp** [comment]
any update on this issue? and also i want to make it adapt dynamic size can some one guide me how should i implement it?
